//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FortuneTellerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerID { get; set; }
        public string CusFirstName { get; set; }
        public string CusLastName { get; set; }
        public int CusAge { get; set; }
        public string CusBirthMonth { get; set; }
        public string FavoriteColor { get; set; }
        public int NumberOfSiblings { get; set; }
    }
}
